name:                aoc18
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/baffalop/aoc18#readme
license:             BSD3
author:              Nikita Gaidakov
maintainer:          nikita.gaidakov@gmail.com
copyright:           2020 Nikita Gaidakov

extra-source-files:
- README.md

dependencies:
- base >= 4.7 && < 5
- containers
- parsec
- optparse-applicative
- extra

executables:
  aoc:
    source-dirs:     src
    main:            Main.hs
